extends: '@waiting/eslint-config/recommended'

rules:
  "@typescript-eslint/no-unused-vars": 0
  "@typescript-eslint/no-var-requires": 0
  "brace-style": 0
  "space-unary-ops": 0
  "@typescript-eslint/semi": ['error','always']

